version: "3"
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./croomgraphDB:/data/db
    restart: unless-stopped
  room:
    build: ./croomgraph/.
    ports:
      - '3000:3000'
    restart: unless-stopped
  backend:
    build: .
    ports:
      - '8080:8080'
    restart: unless-stopped


