import TemporaryDrawer from "@/component/Sidebat"
import Head from "next/head"
import { StyledEngineProvider } from '@mui/material/styles';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">

      <body>
      <StyledEngineProvider injectFirst>
        <TemporaryDrawer/>
        <h1>TEST ME</h1>
        {children}
        </StyledEngineProvider>
        </body>
    </html>
  )
}
