import TemporaryDrawer from "@/component/Sidebat"
import { StyledEngineProvider } from '@mui/material/styles';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">

      <body>
      <StyledEngineProvider injectFirst>
      <AppRouterCacheProvider>
     
        <TemporaryDrawer/>
      <div className="mainDiv">
        {children}
        </div>
        </AppRouterCacheProvider>
        </StyledEngineProvider>
        </body>
    </html>
  )
}
